version: "3"
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_DEFAULT_USER: guest
    networks:
      - backend
  heavy_generator_service:
    build:
      context: ./services/heavy_generator
      dockerfile: Dockerfile
    volumes:
      - ./services/heavy_generator:/app
    environment:
      RABBITMQ_URL: "amqp://rabbitmq:5672"
    entrypoint: ["npm", "start"]
    depends_on:
      - rabbitmq
    networks:
      - backend
  generator_service:
      ports:
        - "3001:3001"
      build:
        context: ./services/generator
        dockerfile: Dockerfile
      volumes:
        - ./services/generator:/app
      environment:
        RABBITMQ_URL: "amqp://rabbitmq:5672"
      entrypoint: ["npm", "start"]
      depends_on:
        - rabbitmq
      networks:
        - frontend
        - backend
networks:
  backend:
    driver: overlay
  frontend:
    driver: overlay