version: "3"
services:
  nginx:
    image: nginx
    volumes:
      - ./nginx:/etc/nginx
    ports:
      - "80:80"
    environment:
      - NGINX_PORT=80
    networks:
      - frontend
    depends_on:
      - generator_service
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_DEFAULT_USER: guest
    networks:
      - backend
  elasticsearch:
    image: elasticsearch
    networks:
      - backend
  kibana:
    image: kibana
    ports:
      - 5601:5601
    networks:
      - frontend
      - backend
  heavy_generator_service:
    build:
      context: ./services/heavy_generator
      dockerfile: Dockerfile
    volumes:
      - ./services/heavy_generator:/app
    environment:
      ELASTICSEARCH_URL: "elasticsearch:9200"
      RABBITMQ_URL: "amqp://rabbitmq:5672"
    entrypoint: ["npm", "start"]
    depends_on:
      - rabbitmq
      - elasticsearch
    networks:
      - backend
  generator_service:
      build:
        context: ./services/generator
        dockerfile: Dockerfile
      volumes:
        - ./services/generator:/app
      environment:
        ELASTICSEARCH_URL: "elasticsearch:9200"
        RABBITMQ_URL: "amqp://rabbitmq:5672"
      entrypoint: ["npm", "start"]
      depends_on:
        - rabbitmq
        - elasticsearch
      networks:
        - frontend
        - backend
networks:
  backend:
    driver: overlay
  frontend:
    driver: overlay
